/**
 * Unit tests for ContactEventHandler persistence behavior.
 *
 * Tests that the handler loads/saves state via ContactStateStore
 * and persists dedup cache across restarts.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { ContactEventHandler } from "../../src/contact-handler.js";
import type { ContactStateStore } from "../../src/contact-state-store.js";
import type { ThenvoiClient } from "../../src/thenvoi-client.js";
import type { ContactEvent } from "../../src/types.js";

function createMockClient(overrides?: Partial<ThenvoiClient>): ThenvoiClient {
  return {
    getParticipants: vi.fn().mockResolvedValue([]),
    createChat: vi.fn().mockResolvedValue({ id: "new-room" }),
    sendEvent: vi.fn().mockResolvedValue({}),
    listContactRequests: vi.fn().mockResolvedValue({ received: [], sent: [] }),
    ...overrides,
  } as unknown as ThenvoiClient;
}

function createMockStore(overrides?: Partial<ContactStateStore>): ContactStateStore {
  return {
    load: vi.fn().mockResolvedValue(null),
    save: vi.fn(),
    flush: vi.fn().mockResolvedValue(undefined),
    ...overrides,
  } as unknown as ContactStateStore;
}

describe("ContactEventHandler persistence", () => {
  let consoleSpy: ReturnType<typeof vi.spyOn>;

  beforeEach(() => {
    consoleSpy = vi.spyOn(console, "log").mockImplementation(() => {});
    vi.spyOn(console, "warn").mockImplementation(() => {});
  });

  describe("loadPersistedState", () => {
    it("should restore dedup cache keys", async () => {
      const store = createMockStore({
        load: vi.fn().mockResolvedValue({
          processedEventKeys: ["contact_added:abc-123"],
          savedAt: "2026-03-08T00:00:00Z",
        }),
      });

      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        stateStore: store,
        onDispatch: vi.fn(),
      });

      await handler.loadPersistedState();

      // The dedup cache should skip a duplicate event
      const event: ContactEvent = {
        type: "contact_added",
        payload: {
          id: "abc-123",
          handle: "@test",
          name: "Test",
          type: "User",
          inserted_at: "2026-03-08T00:00:00Z",
        },
      };

      await handler.handle(event);
      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringContaining("Skipping duplicate"),
      );
    });

    it("should be a no-op without a state store", async () => {
      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        onDispatch: vi.fn(),
      });

      // Should not throw
      await handler.loadPersistedState();
    });

    it("should be a no-op when store returns null", async () => {
      const store = createMockStore({
        load: vi.fn().mockResolvedValue(null),
      });

      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        stateStore: store,
        onDispatch: vi.fn(),
      });

      await handler.loadPersistedState();
      expect(store.load).toHaveBeenCalled();
    });
  });

  describe("markProcessed persistence", () => {
    it("should persist state after marking event as processed", async () => {
      const store = createMockStore();

      const onDispatch = vi.fn().mockResolvedValue(undefined);
      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        stateStore: store,
        onDispatch,
      });

      const event: ContactEvent = {
        type: "contact_added",
        payload: {
          id: "new-contact",
          handle: "@newuser",
          name: "New User",
          type: "User",
          inserted_at: "2026-03-08T00:00:00Z",
        },
      };

      await handler.handle(event);

      // State should have been persisted with the new dedup key (savedAt is generated by the store)
      expect(store.save).toHaveBeenCalledWith(
        expect.objectContaining({
          processedEventKeys: ["contact_added:new-contact"],
        }),
      );
    });
  });

  describe("hub room state", () => {
    it("should persist hub room ID on set", () => {
      const store = createMockStore();
      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        stateStore: store,
        onDispatch: vi.fn(),
      });

      handler.setHubRoomId("hub-room-abc");
      expect(handler.getHubRoomId()).toBe("hub-room-abc");
      expect(store.save).toHaveBeenCalledWith(
        expect.objectContaining({ hubRoomId: "hub-room-abc" }),
      );
    });

    it("should persist hub room initialized flag", () => {
      const store = createMockStore();
      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        stateStore: store,
        onDispatch: vi.fn(),
      });

      handler.setHubRoomInitialized(true);
      expect(handler.isHubRoomInitialized()).toBe(true);
      expect(store.save).toHaveBeenCalledWith(
        expect.objectContaining({ hubRoomInitialized: true }),
      );
    });

    it("should restore hub room state from persisted state", async () => {
      const store = createMockStore({
        load: vi.fn().mockResolvedValue({
          processedEventKeys: [],
          hubRoomId: "hub-room-restored",
          hubRoomInitialized: true,
          savedAt: "2026-03-08T00:00:00Z",
        }),
      });

      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        stateStore: store,
        onDispatch: vi.fn(),
      });

      await handler.loadPersistedState();
      expect(handler.getHubRoomId()).toBe("hub-room-restored");
      expect(handler.isHubRoomInitialized()).toBe(true);
    });

    it("should default hub room state when not persisted", async () => {
      const store = createMockStore({
        load: vi.fn().mockResolvedValue({
          processedEventKeys: ["key1"],
          savedAt: "2026-03-08T00:00:00Z",
        }),
      });

      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        stateStore: store,
        onDispatch: vi.fn(),
      });

      await handler.loadPersistedState();
      expect(handler.getHubRoomId()).toBeNull();
      expect(handler.isHubRoomInitialized()).toBe(false);
    });
  });

  describe("request cache persistence", () => {
    it("should restore request cache from persisted state", async () => {
      const store = createMockStore({
        load: vi.fn().mockResolvedValue({
          processedEventKeys: [],
          requestCache: [
            { key: "req-1", value: { from_handle: "@alice", from_name: "Alice", message: "hi" } },
          ],
          savedAt: "2026-03-08T00:00:00Z",
        }),
      });

      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        stateStore: store,
        onDispatch: vi.fn(),
      });

      await handler.loadPersistedState();

      // Verify cache was restored by checking stats
      const stats = handler.getStats();
      expect(stats.requestCacheSize).toBe(1);
    });

    it("should persist request cache after handling a request event", async () => {
      const store = createMockStore();
      const onDispatch = vi.fn().mockResolvedValue(undefined);
      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        stateStore: store,
        onDispatch,
      });

      const event: ContactEvent = {
        type: "contact_request_received",
        payload: {
          id: "req-new",
          from_handle: "@bob",
          from_name: "Bob",
          message: "hello",
          status: "pending",
          inserted_at: "2026-03-08T00:00:00Z",
        },
      };

      await handler.handle(event);

      expect(store.save).toHaveBeenCalledWith(
        expect.objectContaining({
          requestCache: expect.arrayContaining([
            { key: "req-new", value: { from_handle: "@bob", from_name: "Bob", message: "hello" } },
          ]),
        }),
      );
    });
  });

  describe("pending broadcasts persistence", () => {
    it("should store and retrieve pending broadcasts", () => {
      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        onDispatch: vi.fn(),
      });

      handler.setPendingBroadcasts(["msg1", "msg2"]);
      const restored = handler.getRestoredBroadcasts();
      expect(restored).toEqual(["msg1", "msg2"]);
      // Second call should return empty (queue drained)
      expect(handler.getRestoredBroadcasts()).toEqual([]);
    });

    it("should restore pending broadcasts from persisted state", async () => {
      const store = createMockStore({
        load: vi.fn().mockResolvedValue({
          processedEventKeys: [],
          pendingBroadcasts: ["@alice is now a contact", "@bob was removed"],
          savedAt: "2026-03-08T00:00:00Z",
        }),
      });

      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        stateStore: store,
        onDispatch: vi.fn(),
      });

      await handler.loadPersistedState();
      const restored = handler.getRestoredBroadcasts();
      expect(restored).toEqual(["@alice is now a contact", "@bob was removed"]);
    });

    it("should persist pending broadcasts via state store", () => {
      const store = createMockStore();
      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        stateStore: store,
        onDispatch: vi.fn(),
      });

      handler.setPendingBroadcasts(["broadcast-msg"]);
      // Trigger a persist via hub room setter (any setter triggers persistState)
      handler.setHubRoomId("room-1");

      expect(store.save).toHaveBeenCalledWith(
        expect.objectContaining({
          pendingBroadcasts: ["broadcast-msg"],
        }),
      );
    });
  });

  describe("flushState", () => {
    it("should flush the state store", async () => {
      const store = createMockStore();
      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        stateStore: store,
        onDispatch: vi.fn(),
      });

      await handler.flushState();
      expect(store.flush).toHaveBeenCalled();
    });

    it("should persist latest state before flushing so pending broadcasts are written", async () => {
      const store = createMockStore();
      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        stateStore: store,
        onDispatch: vi.fn(),
      });

      // Set broadcasts without any other persistState trigger
      handler.setPendingBroadcasts(["msg-before-flush"]);
      await handler.flushState();

      // save() should have been called with the broadcasts before flush()
      expect(store.save).toHaveBeenCalledWith(
        expect.objectContaining({
          pendingBroadcasts: ["msg-before-flush"],
        }),
      );
      const saveOrder = vi.mocked(store.save).mock.invocationCallOrder[0];
      const flushOrder = vi.mocked(store.flush).mock.invocationCallOrder[0];
      expect(saveOrder).toBeLessThan(flushOrder);
    });

    it("should be safe without a state store", async () => {
      const handler = new ContactEventHandler({
        config: { strategy: "direct" },
        client: createMockClient(),
        onDispatch: vi.fn(),
      });

      // Should not throw
      await handler.flushState();
    });
  });
});
