/**
 * Unit tests for MCP tools.
 *
 * Now that tools are generated by the SDK's buildRoomScopedRegistrations,
 * these tests verify the integration layer: tool discovery, schema shapes,
 * execution routing through AgentTools, and error handling.
 *
 * The SDK's AgentTools.executeToolCall() returns results directly from the
 * REST API — the response shapes are defined by the SDK, not by this plugin.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import {
  mcpTools,
  getMcpTool,
  executeMcpTool,
  getMcpToolSchemas,
} from "../../src/mcp-tools.js";
import * as channel from "../../src/channel.js";

// Mock the channel module
vi.mock("../../src/channel.js", () => ({
  getLink: vi.fn(),
  getAgentId: vi.fn(),
}));

// Mock REST API methods matching SDK's RestApi interface
const mockRest = {
  getAgentMe: vi.fn(),
  listPeers: vi.fn(),
  addChatParticipant: vi.fn(),
  removeChatParticipant: vi.fn(),
  listChatParticipants: vi.fn(),
  createChat: vi.fn(),
  createChatMessage: vi.fn(),
  createChatEvent: vi.fn(),
  listContacts: vi.fn(),
  addContact: vi.fn(),
  removeContact: vi.fn(),
  listContactRequests: vi.fn(),
  respondContactRequest: vi.fn(),
};

const mockLink = {
  rest: mockRest,
  agentId: "agent-123",
  capabilities: { peers: true, contacts: true, memory: false },
};

beforeEach(() => {
  vi.clearAllMocks();
  vi.mocked(channel.getLink).mockReturnValue(mockLink as unknown as ReturnType<typeof channel.getLink>);
  vi.mocked(channel.getAgentId).mockReturnValue("agent-123");
});

describe("MCP Tools", () => {
  // =========================================================================
  // Tool Discovery & Schema
  // =========================================================================

  describe("tool discovery", () => {
    it("should have tools registered from SDK", () => {
      expect(mcpTools.length).toBeGreaterThan(0);
    });

    it("should include core room tools", () => {
      const names = mcpTools.map((t) => t.name);
      expect(names).toContain("thenvoi_send_message");
      expect(names).toContain("thenvoi_send_event");
      expect(names).toContain("thenvoi_add_participant");
      expect(names).toContain("thenvoi_remove_participant");
      expect(names).toContain("thenvoi_get_participants");
      expect(names).toContain("thenvoi_create_chatroom");
      expect(names).toContain("thenvoi_lookup_peers");
    });

    it("should include contact tools", () => {
      const names = mcpTools.map((t) => t.name);
      expect(names).toContain("thenvoi_list_contacts");
      expect(names).toContain("thenvoi_add_contact");
      expect(names).toContain("thenvoi_remove_contact");
      expect(names).toContain("thenvoi_list_contact_requests");
      expect(names).toContain("thenvoi_respond_contact_request");
    });

    it("should NOT include memory tools", () => {
      const names = mcpTools.map((t) => t.name);
      const memoryTools = names.filter((n) => n.includes("memory"));
      expect(memoryTools).toHaveLength(0);
    });

    it("should have room_id in all tool schemas (room-scoped)", () => {
      for (const tool of mcpTools) {
        expect(tool.inputSchema.properties).toHaveProperty("room_id");
        expect(tool.inputSchema.required).toContain("room_id");
      }
    });
  });

  describe("getMcpTool", () => {
    it("should find tool by name", () => {
      const tool = getMcpTool("thenvoi_send_message");
      expect(tool).toBeDefined();
      expect(tool?.name).toBe("thenvoi_send_message");
    });

    it("should return undefined for unknown tool", () => {
      expect(getMcpTool("nonexistent")).toBeUndefined();
    });
  });

  describe("getMcpToolSchemas", () => {
    it("should return schemas for all tools", () => {
      const schemas = getMcpToolSchemas();
      expect(schemas.length).toBe(mcpTools.length);
      for (const schema of schemas) {
        expect(schema).toHaveProperty("name");
        expect(schema).toHaveProperty("description");
        expect(schema).toHaveProperty("inputSchema");
        expect(schema.inputSchema.type).toBe("object");
      }
    });
  });

  describe("executeMcpTool", () => {
    it("should throw for unknown tool", async () => {
      await expect(executeMcpTool("nonexistent", {})).rejects.toThrow(
        "Unknown tool: nonexistent",
      );
    });
  });

  // =========================================================================
  // Tool Execution (through SDK's AgentTools)
  //
  // The SDK's executeToolCall() returns results directly from the REST API.
  // We verify: (1) the correct REST method was called, (2) a result is returned.
  // =========================================================================

  describe("thenvoi_lookup_peers", () => {
    it("should call listPeers and return results", async () => {
      mockRest.listPeers.mockResolvedValue({
        data: [
          { id: "agent-1", name: "Agent One", type: "Agent", handle: "@agent-one", description: "Test" },
        ],
        metadata: { page: 1, pageSize: 50, totalCount: 1, totalPages: 1 },
      });

      const result = await executeMcpTool("thenvoi_lookup_peers", {
        room_id: "room-001",
      });

      expect(mockRest.listPeers).toHaveBeenCalled();
      expect(result).toBeDefined();
    });
  });

  describe("thenvoi_get_participants", () => {
    it("should call listChatParticipants and return results", async () => {
      mockRest.listChatParticipants.mockResolvedValue([
        { id: "user-789", name: "John Doe", type: "User" },
        { id: "agent-123", name: "Test Agent", type: "Agent" },
      ]);

      const result = await executeMcpTool("thenvoi_get_participants", {
        room_id: "room-001",
      });

      expect(mockRest.listChatParticipants).toHaveBeenCalled();
      expect(result).toBeDefined();
    });
  });

  describe("thenvoi_create_chatroom", () => {
    it("should call createChat and return result", async () => {
      mockRest.createChat.mockResolvedValue({ id: "room-new-001" });

      const result = await executeMcpTool("thenvoi_create_chatroom", {
        room_id: "room-001",
      });

      expect(mockRest.createChat).toHaveBeenCalled();
      expect(result).toBeDefined();
    });
  });

  describe("thenvoi_send_event", () => {
    it("should call createChatEvent", async () => {
      mockRest.createChatEvent.mockResolvedValue({ ok: true, id: "event-001" });

      const result = await executeMcpTool("thenvoi_send_event", {
        room_id: "room-001",
        content: "Thinking about this...",
        message_type: "thought",
      });

      expect(mockRest.createChatEvent).toHaveBeenCalled();
      expect(result).toBeDefined();
    });
  });

  describe("thenvoi_send_message", () => {
    it("should call createChatMessage with resolved mentions", async () => {
      mockRest.listChatParticipants.mockResolvedValue([
        { id: "user-789", name: "John Doe", type: "User" },
        { id: "agent-123", name: "Test Agent", type: "Agent" },
      ]);
      mockRest.createChatMessage.mockResolvedValue({ ok: true, id: "msg-001" });

      const result = await executeMcpTool("thenvoi_send_message", {
        room_id: "room-001",
        content: "Hello!",
        mentions: ["John Doe"],
      });

      expect(mockRest.listChatParticipants).toHaveBeenCalled();
      expect(mockRest.createChatMessage).toHaveBeenCalled();
      expect(result).toBeDefined();
    });

    it("should require mentions", async () => {
      await expect(
        executeMcpTool("thenvoi_send_message", {
          room_id: "room-001",
          content: "Hello!",
          mentions: [],
        }),
      ).rejects.toThrow();
    });
  });

  describe("thenvoi_add_participant", () => {
    it("should lookup peer and add to room", async () => {
      // SDK's add_participant uses "name" param (not "handle")
      mockRest.listPeers.mockResolvedValue({
        data: [
          { id: "agent-weather", name: "Weather Agent", type: "Agent", handle: "@weather-agent" },
        ],
        metadata: { page: 1, pageSize: 100, totalCount: 1, totalPages: 1 },
      });
      mockRest.addChatParticipant.mockResolvedValue({ ok: true });

      const result = await executeMcpTool("thenvoi_add_participant", {
        room_id: "room-001",
        name: "Weather Agent",
      });

      expect(mockRest.listPeers).toHaveBeenCalled();
      expect(mockRest.addChatParticipant).toHaveBeenCalled();
      expect(result).toBeDefined();
    });
  });

  describe("thenvoi_remove_participant", () => {
    it("should resolve name and remove participant", async () => {
      mockRest.listChatParticipants.mockResolvedValue([
        { id: "user-789", name: "John Doe", type: "User" },
        { id: "agent-123", name: "Test Agent", type: "Agent" },
      ]);
      mockRest.removeChatParticipant.mockResolvedValue({ ok: true });

      const result = await executeMcpTool("thenvoi_remove_participant", {
        room_id: "room-001",
        name: "John Doe",
      });

      expect(mockRest.listChatParticipants).toHaveBeenCalled();
      expect(mockRest.removeChatParticipant).toHaveBeenCalled();
      expect(result).toBeDefined();
    });
  });

  // =========================================================================
  // Contact Tools
  // =========================================================================

  describe("thenvoi_list_contacts", () => {
    it("should call listContacts", async () => {
      mockRest.listContacts.mockResolvedValue({
        data: [{ id: "c1", handle: "@jane", name: "Jane", type: "User" }],
        metadata: { page: 1, pageSize: 50, totalCount: 1, totalPages: 1 },
      });

      const result = await executeMcpTool("thenvoi_list_contacts", {
        room_id: "room-001",
      });

      expect(mockRest.listContacts).toHaveBeenCalled();
      expect(result).toBeDefined();
    });
  });

  describe("thenvoi_add_contact", () => {
    it("should call addContact", async () => {
      mockRest.addContact.mockResolvedValue({ id: "req-001", status: "pending" });

      const result = await executeMcpTool("thenvoi_add_contact", {
        room_id: "room-001",
        handle: "@jane",
      });

      expect(mockRest.addContact).toHaveBeenCalled();
      expect(result).toBeDefined();
    });
  });

  describe("thenvoi_remove_contact", () => {
    it("should call removeContact", async () => {
      mockRest.removeContact.mockResolvedValue({ ok: true });

      const result = await executeMcpTool("thenvoi_remove_contact", {
        room_id: "room-001",
        handle: "@jane",
      });

      expect(mockRest.removeContact).toHaveBeenCalled();
      expect(result).toBeDefined();
    });
  });

  describe("thenvoi_list_contact_requests", () => {
    it("should call listContactRequests", async () => {
      mockRest.listContactRequests.mockResolvedValue({
        received: [{ id: "r1", from_handle: "@alice", status: "pending" }],
        sent: [],
        metadata: { page: 1, pageSize: 50 },
      });

      const result = await executeMcpTool("thenvoi_list_contact_requests", {
        room_id: "room-001",
      });

      expect(mockRest.listContactRequests).toHaveBeenCalled();
      expect(result).toBeDefined();
    });
  });

  describe("thenvoi_respond_contact_request", () => {
    it("should call respondContactRequest", async () => {
      mockRest.respondContactRequest.mockResolvedValue({ id: "r1", status: "approved" });

      const result = await executeMcpTool("thenvoi_respond_contact_request", {
        room_id: "room-001",
        action: "approve",
        handle: "@alice",
      });

      expect(mockRest.respondContactRequest).toHaveBeenCalled();
      expect(result).toBeDefined();
    });
  });

  // =========================================================================
  // Error: link not connected
  // =========================================================================

  describe("error handling", () => {
    it("should throw when link not connected", async () => {
      vi.mocked(channel.getLink).mockReturnValue(undefined);

      await expect(
        executeMcpTool("thenvoi_lookup_peers", { room_id: "room-001" }),
      ).rejects.toThrow();
    });
  });
});
